### ISSUE TITLE
Docker Build Error for ELK/Logstash

### ISSUE THREAD

**Issue by adrianwinckles** [OWASP/Honeypot-Project#13]
When building the docker image (i.e docker-compose build) for ELK/Logstash

Most of the build completes but near the end 

/bin/sh: 1: wget: not found
ERROR: Service 'modsec_crs' failed to build: The command '/bin/sh -c wget  https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-5.1.2-x86_64.rpm' returned a non-zero code: 127

Any thoughts?

**Comment by fzipi** [comment]
@adrianwinckles Have this been corrected by the latest merge?

**Comment by adrianwinckles** [comment]
Yes,think so when I last tested
