### ISSUE TITLE
Logging alternatives

### ISSUE THREAD

**Issue by fzipi** [OWASP/Honeypot-Project#8]
Consider new alternatives for log transfer including the use of:

- MLOGC-NG
- FileBeat (Logstash)
- You name it..

**Comment by fzipi** [comment]
@tulja If we are interested, we should provide documentation on the setup for at least `mlogc-ng` or `mlogc` based modsecurity. That way we can have also "legacy" (non-json loggers) and sent them properly to elk.

**Comment by tulja** [comment]
@fzipi, Sure I will work on it.
